# Write a program to input eight numbers from the user and display all the unique numbers(once).

s = set()
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)
num = int(input("Enter number: "))
s.add(num)

print(s)